### ISSUE TITLE
calling latexmls no longer works reliably

### ISSUE THREAD

**Issue by cmaeder** [dginev/LaTeXML-Plugin-latexmls#4]
see https://github.com/KWARC/localmh/issues/296

**Comment by cmaeder** [comment]
some the java process hangs when reading stdout.

**Comment by dginev** [comment]
This is a really bad issue report for me, I have no idea how you're using latexmls and what exactly your issue is.

You're not supposed to "call" latexmls itself, as it is not a client executable, it is a socket server that communicates on a given socket. So even the subject line is confusing.

Please provide a detailed report and I'll be happy to take a look.

**Comment by cmaeder** [comment]
My process handle closes the output stream and only expects "output" on stderr. I think, that is the problem. So it is indeed my fault calling "latexmls" as a daemon process.

**Comment by dginev** [comment]
the print your mentioned should've happened on STDERR in the first place, I'll move it now.

**Comment by dginev** [comment]
done.

**Comment by cmaeder** [comment]
Thanks, I've also patched the mmt side https://github.com/KWARC/MMT/commit/e3bc4a4f583a2cea1ee52198bbb9cfc88487b4e8
